### PR TITLE
ArmorStands

### PR DESCRIPTION
**Pull request by Enes5519**
**TODO**
- [x] Add Entity
- [x] Added interact for entity
- [x] Added event for entity interact
- [x] Remove items from armor stands
- [x] Pose

### CODE REVIEW

**Comment by NycuRO** [comment]
rip reformat , rip all hacky.

It's not EntityInteractEvent, is PlayerClickEvent.

**Comment by Enes5519** [comment]
@NycuRO you right. sorry for my bad eng.

**Comment by Enes5519** [comment]
Finished :D ! Is there a problem?

**Comment by NycuRO** [comment]
Lmaoooo ✌️ 

Already exist PlayerInteractEvent =))))))))
Lmao, you really noob on this.

**Comment by SuperKali** [comment]
@Enes5519 good! 
work fine

**Comment by SuperKali** [comment]
@NycuRO you are serious?

**Comment by SuperKali** [comment]
you can not judge the work of others, so please close the discussion

**Comment by Enes5519** [comment]
1- You are idiot.
2- I created the PlayerEntityInteractEvent class because I wanted the PlayerInteractEvent class to be specific to the blocks.
3- TeaSpoon is plugin not software. Altay is software.
4- I don't think it's an accurate comparison. But if you say it's a feature, we're just starting :D.

**Pull request merged**
